// <auto-generated />
namespace Buku.API.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class editO2mNremove : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(editO2mNremove));
        
        string IMigrationMetadata.Id
        {
            get { return "201611070258371_editO2mNremove"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
