// <auto-generated />
namespace Buku.API.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class student_studentId : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(student_studentId));
        
        string IMigrationMetadata.Id
        {
            get { return "201611041004257_student_studentId"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
