// <auto-generated />
namespace Buku.API.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Add_O2m_OStudentMBook_rev : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_O2m_OStudentMBook_rev));
        
        string IMigrationMetadata.Id
        {
            get { return "201611041008040_Add_O2m_OStudentMBook_rev"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
